version: '3'
services:
  web:
    image: nginx:1.17-alpine
    container_name: myweb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    ports:
      - 80:80
networks:
  default:
    external:
      name: mynw